mongo_data:
  image: busybox
  volumes:
    - /data/db
  command: sh -c "while true; do echo "hello"; sleep 1d; done;"

mongo:
  image: mongo:3.2
  ports:
    - 27017:27017
  expose:
    - 270107
  volumes_from:
    - mongo_data

admin:
  image: knickers/mongo-express:latest
  links: 
    - mongo
  ports:
    - 8081:8081
  
