version: '2'

services:
  mongo:
    image: mongo:3.2
    ports:
      - 27017:27017
    expose:
      - 270107
    volumes:
      - mongo_data:/data/db

  admin:
    image: knickers/mongo-express:latest
    links: 
      - mongo
    ports:
      - 8990:8081

volumes:
  mongo_data:
    driver: local
  
